services:
  - type: web
    name: mini-soar
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn.conf.py app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        sync: false
      - key: ABUSEIPDB_API_KEY
        sync: false
      - key: VIRUSTOTAL_API_KEY
        sync: false
      - key: SHODAN_API_KEY
        sync: false